Repository chaeeun-Han/Metanet-Final-Project-Team-2-FE, pull requests merged in 2025-02, with the labels that each got.

#6 [Feature] 로그인 화면 구현
  MetanetProjectFE/package-lock.json
  MetanetProjectFE/package.json
  MetanetProjectFE/public/assets/css/style.bundle.css
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/Account/Account_chart_widget.vue
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/login/Login_Input.vue
  MetanetProjectFE/src/components/login/Login_background.vue
  MetanetProjectFE/src/components/login/Login_content.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/components/login/Login_main.vue
  MetanetProjectFE/src/router/index.js
Labels: feature, refactor

#11 [Feature] 마이페이지 구현
  MetanetProjectFE/src/components/Account/Account_ToolBar.vue
  MetanetProjectFE/src/components/Account/Account_chart_widget.vue
  MetanetProjectFE/src/components/Account/Account_content.vue
  MetanetProjectFE/src/components/Account/Account_editprofile.vue
  MetanetProjectFE/src/components/Account/Account_items.vue
  MetanetProjectFE/src/components/Account/Account_lecture.vue
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Account/Account_mylecture.vue
  MetanetProjectFE/src/components/Account/Account_mystudy.vue
  MetanetProjectFE/src/components/Account/Account_mystudylist.vue
  MetanetProjectFE/src/components/Account/Account_overview.vue
  MetanetProjectFE/src/components/Account/Account_paylist.vue
  MetanetProjectFE/src/components/Account/Account_profile_detail.vue
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/router/index.js
Labels: feature

#13 [Feature] 메인페이지 추가
  MetanetProjectFE/src/apis/api.js
  MetanetProjectFE/src/apis/apiService.js
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/lecture-box/Lecture_box.vue
  MetanetProjectFE/src/components/lecture-box/Lecture_list_item.vue
  MetanetProjectFE/src/components/lecture/LectuerHeader.vue
  MetanetProjectFE/src/components/lecture/Lecture_content.vue
  MetanetProjectFE/src/components/lecture/Lecture_main.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_file.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_intro.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_qna.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/components/main/main_main.vue
  MetanetProjectFE/src/router/index.js
Labels: feature

#12 [Feature] QnA 화면 구현 - 질문 목록 페이지
  MetanetProjectFE/package-lock.json
  MetanetProjectFE/package.json
  MetanetProjectFE/public/assets/media/profile.png
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/components/qna/QnaList.vue
  MetanetProjectFE/src/components/qna/QuestionDetail.vue
  MetanetProjectFE/src/router/index.js
  MetanetProjectFE/vite.config.js
Labels: feature

#16 [Feature] QnA 화면 구현 - 질문 상세 페이지
  MetanetProjectFE/src/components/lecture-box/Lecture_box.vue
  MetanetProjectFE/src/components/lecture-box/Lecture_list_item.vue
  MetanetProjectFE/src/components/lecture/Lecture_content.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_qna.vue
  MetanetProjectFE/src/components/qna/QuestionDetail.vue
  MetanetProjectFE/src/router/index.js
Labels: feature

#18 [Feature] QnA 화면 구현 - 질문 상세 페이지 추가
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_intro.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_qna.vue
  MetanetProjectFE/src/components/qna/QnaList.vue
  MetanetProjectFE/src/components/qna/QuestionDetail.vue
  MetanetProjectFE/src/components/qna/QuestionWrite.vue
Labels: feature

#20 [fix] import name error
  MetanetProjectFE/src/components/login/Login_form.vue
Labels: fix

#22 [Feat] 알림창 추가
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/apis/api.js
  MetanetProjectFE/src/apis/apiService.js
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/components/qna/QuestionDetail.vue
  MetanetProjectFE/src/components/qna/QuestionWrite.vue
Labels: feature

#26 Hce cart 8
  MetanetProjectFE/index.html
  MetanetProjectFE/package-lock.json
  MetanetProjectFE/package.json
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/Account/Account_ToolBar.vue
  MetanetProjectFE/src/components/Cart/Cart_content.vue
  MetanetProjectFE/src/components/Cart/Cart_main.vue
  MetanetProjectFE/src/components/Cart/toss/Success.vue
  MetanetProjectFE/src/router/index.js
Labels: feature

#29 [Fix] fixed import name error
  MetanetProjectFE/src/components/Account/Account_ToolBar.vue
  MetanetProjectFE/src/components/Account/Account_lecture.vue
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Account/Account_mylecture.vue
  MetanetProjectFE/src/components/Account/Account_mystudylist.vue
  MetanetProjectFE/src/components/Account/Account_overview.vue
  MetanetProjectFE/src/components/Account/Account_paylist.vue
  MetanetProjectFE/src/components/Account/Account_revenue.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_intro.vue
Labels: fix

#30 [Feat] 회원가입 페이지 구현
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/components/signup/Signup.vue
  MetanetProjectFE/src/components/signup/signup_input.vue
  MetanetProjectFE/src/router/index.js
Labels: feature

#32 [Feature] 국제화(i18n)
  MetanetProjectFE/package-lock.json
  MetanetProjectFE/package.json
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/main/main_main.vue
  MetanetProjectFE/src/i18n.js
  MetanetProjectFE/src/locales/en.json
  MetanetProjectFE/src/locales/ko.json
  MetanetProjectFE/src/main.js
Labels: feature

#38 [Fix] sessionStorage bug
  MetanetProjectFE/src/App.vue
Labels: bug

#40 [Feature] 관리자 마이페이지 구현 및 마이페이지 권한에 따른 페이지 설정
  MetanetProjectFE/package-lock.json
  MetanetProjectFE/package.json
  MetanetProjectFE/src/components/Account/Account_ToolBar.vue
  MetanetProjectFE/src/components/Account/Account_adminDashboard.vue
  MetanetProjectFE/src/components/Account/Account_editprofile.vue
  MetanetProjectFE/src/components/Account/Account_lecture.vue
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Account/Account_mylecture.vue
  MetanetProjectFE/src/components/Account/Account_mystudy.vue
  MetanetProjectFE/src/components/Account/Account_mystudylist.vue
  MetanetProjectFE/src/components/Account/Account_overview.vue
  MetanetProjectFE/src/components/Account/Account_paylist.vue
  MetanetProjectFE/src/components/Account/Account_revenue.vue
  MetanetProjectFE/src/components/Account/Account_viewlecture.vue
  MetanetProjectFE/src/components/Account/Account_viewmember.vue
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/password-reset/Password_confirm.vue
  MetanetProjectFE/src/components/password-reset/Password_reset.vue
  MetanetProjectFE/src/locales/en.json
  MetanetProjectFE/src/locales/ko.json
  MetanetProjectFE/src/router/index.js
Labels: feature

#44 feat : Modify style password_confirm (#41)
  MetanetProjectFE/src/components/password-reset/Password_confirm.vue
Labels: fix

#45 [Feature] 권한 처리 구현
  MetanetProjectFE/public/assets/media/auth/403-error.png
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Error/Error403Page.vue
  MetanetProjectFE/src/components/Error/Error404Page.vue
  MetanetProjectFE/src/components/Error/Error500Page.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/main.js
  MetanetProjectFE/src/router/index.js
Labels: feature

#49 [Feature] 강의 추가 페이지 추가
  MetanetProjectFE/src/apis/api.js
  MetanetProjectFE/src/components/Account/Account_ToolBar.vue
  MetanetProjectFE/src/components/Account/Account_editprofile.vue
  MetanetProjectFE/src/components/Account/Account_input.vue
  MetanetProjectFE/src/components/Account/Account_input_lecture.vue
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Cart/Cart_content.vue
  MetanetProjectFE/src/components/Cart/toss/Success.vue
  MetanetProjectFE/src/components/lecture/LectuerHeader.vue
  MetanetProjectFE/src/components/lecture/Lecture_content.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_file.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_intro.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_qna.vue
Labels: feature, fix

#50 [Feature] 메인화면 ui 수정
  MetanetProjectFE/index.html
  MetanetProjectFE/src/components/Header/Header.vue
  MetanetProjectFE/src/components/lecture-box/Lecture_box.vue
  MetanetProjectFE/src/components/lecture-box/Lecture_list_item.vue
  MetanetProjectFE/src/components/main/main_main.vue
  MetanetProjectFE/src/locales/en.json
  MetanetProjectFE/src/locales/ko.json
Labels: refactor

#52 [Fix] Toss 구매 기능 수리, 강의 자료 다운로드 조건 추가
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Cart/Cart_content.vue
  MetanetProjectFE/src/components/Cart/toss/Success.vue
  MetanetProjectFE/src/components/lecture/LectuerHeader.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_file.vue
  MetanetProjectFE/src/components/lecture/lecture-inner/Lecture_intro.vue
Labels: feature, fix

#55 [Style] 회원가입, 로그인, 이메일 인증 ui 수정
  MetanetProjectFE/public/assets/media/auth/auth-bg.png
  MetanetProjectFE/public/assets/media/login_background.png
  MetanetProjectFE/public/assets/media/login_img.png
  MetanetProjectFE/public/assets/media/white-logo.png
  MetanetProjectFE/src/components/login/Login_Input.vue
  MetanetProjectFE/src/components/login/Login_background.vue
  MetanetProjectFE/src/components/login/Login_content.vue
  MetanetProjectFE/src/components/login/Login_form.vue
  MetanetProjectFE/src/components/password-reset/Password_confirm.vue
  MetanetProjectFE/src/components/signup/Signup.vue
  MetanetProjectFE/src/components/signup/signup_input.vue
Labels: refactor

#58 [Fix] Excel 다운로드 기능 수정
  MetanetProjectFE/src/components/Account/Account_input.vue
  MetanetProjectFE/src/components/Account/Account_lecture.vue
Labels: fix

#60 [Fix] FE account url format
  MetanetProjectFE/src/components/Account/Account_adminDashboard.vue
  MetanetProjectFE/src/components/Account/Account_editprofile.vue
  MetanetProjectFE/src/components/Account/Account_main.vue
  MetanetProjectFE/src/components/Account/Account_mystudylist.vue
  MetanetProjectFE/src/components/Account/Account_overview.vue
  MetanetProjectFE/src/components/Account/Account_paylist.vue
  MetanetProjectFE/src/components/Account/Account_revenue.vue
  MetanetProjectFE/src/components/Account/Account_viewlecture.vue
  MetanetProjectFE/src/components/Account/Account_viewmember.vue
Labels: fix

#63 [Refactor] api.js를 이용한 요청 방식 수정
  MetanetProjectFE/index.html
  MetanetProjectFE/public/assets/media/cursor.png
  MetanetProjectFE/src/App.vue
  MetanetProjectFE/src/components/Cart/Cart_content.vue
  MetanetProjectFE/src/components/LoginForm.vue
  MetanetProjectFE/src/components/Sidebar/Sidebar.vue
  MetanetProjectFE/src/components/Signup.vue
  MetanetProjectFE/src/components/login/Login_form.vue
Labels: refactor

#65 refactor: Rename page (#64)
  MetanetProjectFE/src/components/qna/Question_detail.vue
  MetanetProjectFE/src/components/qna/Question_write.vue
  MetanetProjectFE/src/router/index.js
Labels: refactor
